### ISSUE TITLE
Classes not found

### ISSUE THREAD

**Issue by ramospedro** [uc-union/union-ads-sdk-unity-demo#1]
Hi,
I've imported the unity package contained in this repo on my Unity project (v 4.6).
In order to test the sdk, I dragged the "Demo" script into an empty object inside my test scene. The apk compiles just fine, but when I try to load an ad it throws a few exceptions about missing classes.

Here is the log from logcat:

> 06-16 15:24:53.080  25207-25240/? I/Unity﹕ AndroidJavaException: java.lang.ClassNotFoundException: com.ucweb.union.ads.UnionAdsSdk
>             at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject](System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject](System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaClass..ctor (System.String className) [0x00000] in <filename unknown>:0
>             at Assets.Mediation_SDK.Library.AdSDK.start () [0x00000] in <filename unknown>:0
>     a
> 06-16 15:24:55.940  25207-25240/? I/Unity﹕ AndroidJavaException: java.lang.ClassNotFoundException: com.ucweb.union.ads.InterstitialAd
>             at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject](System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject](System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0
>             at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x00000] in <filename unknown>:0
>             at Assets.Mediation_SDK.Library.Int

**Comment by ramospedro** [comment]
The issue was actually regarding my Unity version. Unity 4.6 doesn't support .aar files.
I can't upgrade to Unity 5 because apks get bigger on this version and we lose competitivity on 9apps.
So I extracted the .jar form unionads.aar and used only the jar. After that I did a few tweaks on the manifest and it worked just fine.

**Comment by niraj126** [comment]
I am facing the same problem . please help me to solve this

**Comment by leeowenowen** [comment]
@niraj126 , just as pedro said, extract the .aar file  and merge  AndroidManifest.xml, proguard.cfg and *.jar。

**Comment by niraj126** [comment]
thank you I will try this .

**Comment by ramospedro** [comment]
Yep, I did just like I said. 
If I still had any project with this SDK here I could send you a manifest sample to make things easy.

Unfortunately I haven't worked with this SDK for a while.

**Comment by niraj126** [comment]
I will try to do as you said. 
thank you for help

**Comment by niraj126** [comment]
I extracted .aar file but I am facing still this error
